LainSimpleGrades/Grades/urls.py
'''
urls.py - Django Standart File Url Routing

This file is part of Lain Simple Grades.

Lain Simple Grades is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Lain Simple Grades is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Lain Simple Grades.  If not, see <https://www.gnu.org/licenses/>.
'''
from django.urls import path
from . import views

#Common
urlpatterns = [
    path('', views.index, name='index'),    
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('userslist/', views.UserListView.as_view(), name='userslist'),
    path('studentlist/<int:pk>', views.StudentListview.as_view(), name='studentlist')
]

#Managers
urlpatterns += [
    path('schoollist/', views.SchoolListView.as_view(), name='schoollist'),
    path('addschool/', views.SchoolCreateView.as_view(), name='addschool'),
    path('editschool/<int:pk>/', views.SchoolUpdateView.as_view(), name='editschool'),
    path('deleteschool/<int:pk>/delete/', views.SchoolDeleteView.as_view(), name='deleteschool'),
    path('addclassroom/', views.ClassRoomCreateView.as_view(), name='addclassroom'),
    path('classroomlist', views.ClassRoomListView.as_view(), name='classroomlist'),
    path('editclassroom/<int:pk>/', views.ClassRoomUpdateView.as_view(), name='editclassroom'),
    path('deleteclassroom/<int:pk>/delete/', views.ClassRoomDeleteView.as_view(), name='deleteclassroom'),
]

#Lecturers
urlpatterns += [
    path('courselist/', views.CourseListview.as_view(), name='courselist'),
    path('addcourse/', views.CourseCreateView.as_view(), name='addcourse'),
    path('editcourse/<int:pk>/', views.CourseUpdateView.as_view(), name='editcourse'),
    path('deletecourse/<int:pk>/delete/', views.CourseDeleteView.as_view(), name='deletecourse'),    
    path('givegrades/<int:pk>', views.GiveGradesView.as_view(), name='givegrades'),    
]

#Students
urlpatterns += [
    path('enroll/<int:pk>/', views.Enroll, name='enroll'),
    path('takencourses/', views.TakenCoursesListView.as_view(), name='takencourses'),
]

LainSimpleGrades/LainSimpleGrades/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
urlpatterns += [
    path('grades/', include('Grades.urls')),
    path('', include('Grades.urls'))
]

urlpatterns += [    
    path('', include('django.contrib.auth.urls')),
]

LainSimpleGrades/Grades/models.py
'''
models.py - Django Standart File Models

This file is part of Lain Simple Grades.

Lain Simple Grades is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Lain Simple Grades is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Lain Simple Grades.  If not, see <https://www.gnu.org/licenses/>.
'''

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

class CustomUser(AbstractUser):
    '''
    Custom User Model for authentication
    '''
    USER_TYPE_CHOICES = (
        (0, 'Admin'),
        (1, 'Student'),
        (2, 'Lecturer'),   
        (3, 'Manager'),
    )

    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=0)
    def __str__(self):
        return self.username

class School(models.Model):
    '''
    School model
    '''
    name = models.CharField(max_length=50, help_text="Enter School Name")
    
    CITY_CHOICES = (        
        (1, 'Istanbul'),
        (2, 'London'),   
        (3, 'Tokyo'),
        (4, 'New York'),
        (5, 'Berlin'),
        (6, 'Moscow'),
    )

    city = models.PositiveSmallIntegerField(choices=CITY_CHOICES, default=1)
    
    def __str__(self):
        return self.name

class ClassRoom(models.Model):
    '''
    ClassRoom in school
    '''
    name = models.CharField(max_length=50, help_text="Enter Classroom Name")
    school = models.ForeignKey('School', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class Course(models.Model):
    '''
    Course model
    '''
    name = models.CharField(max_length=50, help_text='Enter Course Name')
    code = models.CharField(max_length=10, help_text='Enter Course Code')    
    classRoom = models.ForeignKey('ClassRoom', on_delete=models.SET_NULL, null=True, help_text='Select Class Room')
    lecturer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='Students', help_text='Students')

    def __str__(self):
        return "{0} ({1})".format(self.name, self.code)


class Take(models.Model):
    '''
    Take model. Student grades.
    '''
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    grade = models.PositiveIntegerField(blank=True, null=True, help_text='Grade', 
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)])
    

LainSimpleGrades/Grades/views.py
'''
Views.py - Django Standart File Views

This file is part of Lain Simple Grades.

Lain Simple Grades is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Lain Simple Grades is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Lain Simple Grades.  If not, see <https://www.gnu.org/licenses/>.
'''
from django.template import loader
from django.http import HttpResponse
from django import views
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.forms import modelformset_factory
from django.views.generic import (CreateView, DeleteView, ListView, FormView, UpdateView)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import  ClassRoom, School, Course, CustomUser, Take
from .forms import SignUpForm, SchoolCreateForm, ClassRoomCreateForm, CourseForm, GiveGradesForm

# Create your views here.
def index(request):
    '''
    Home Page
    '''
    print('index called')
    return render(request, 'index.html')

class SignUp(CreateView):
    '''
    New User Signup
    '''
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        role = form.cleaned_data['role']
        obj.user_type = role
        form.save()
        return super().form_valid(form)

class UserListView(LoginRequiredMixin, ListView):
    '''
    Users List
    '''
    model = CustomUser
    ordering = ('name', )
    context_object_name = 'Users'
    template_name = 'userslist.html'
    raise_exception = True

    def test_func(self):
        print('UserListview UserType:{0}'.format(self.request.user.user_type)) 
        return True

    def get_queryset(self):
        return CustomUser.objects.order_by('user_type')

class SchoolListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''
    School List
    '''
    model = School
    ordering = ('name', )
    context_object_name = 'Schools'
    template_name = 'Manager/schoollist.html'
    raise_exception = True

    def test_func(self):
        print('SchoolListview UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_queryset(self):
        return School.objects.order_by('name')

class SchoolCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    '''
    School Create
    '''
    model = School
    form_class = SchoolCreateForm
    template_name = 'Manager/school.html'
    success_url = reverse_lazy('schoollist')
    raise_exception = True

    def test_func(self):
        print('SchoolCreatView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('not authenticated')
            return super(SchoolCreateView, self).get_login_url()
        return ''      

    def get_context_data(self, **kwargs):
        context = super(SchoolCreateView, self).get_context_data(**kwargs)
        context['title'] = "Add School"
        return context  

class SchoolUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''
    Update School
    '''
    model = School
    form_class = SchoolCreateForm
    template_name = 'Manager/school.html'
    success_url = reverse_lazy('schoollist')
    raise_exception = True

    def test_func(self):
        print('SchoolUpdateView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True
    
    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('not authenticated')
            return super(SchoolUpdateView, self).get_login_url()
        return ''      

    def get_context_data(self, **kwargs):
        context = super(SchoolUpdateView, self).get_context_data(**kwargs)
        context['title'] = "Modify School"
        return context  

class SchoolDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    '''
    Delete School
    '''
    model = School
    fields = ('id', 'name', 'city')
    context_object_name = 'school'
    success_url = reverse_lazy('schoollist')
    template_name = 'Manager/deleteschool.html'
    raise_exception = True

    def test_func(self):
        print('SchoolDeleteView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

class ClassRoomListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''
    Class Room List
    '''
    model = ClassRoom
    ordering = ('name', )
    context_object_name = 'ClassRooms'
    template_name = 'Manager/classroomlist.html'
    raise_exception = True

    def test_func(self):
        print('ClassRoomListView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_queryset(self):
        return ClassRoom.objects.order_by('school')

class ClassRoomCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    '''
    Create Class Room
    '''
    model = ClassRoom
    form_class = ClassRoomCreateForm
    success_url = reverse_lazy('classroomlist')
    template_name = 'Manager/classroom.html'
    raise_exception = True

    def test_func(self):
        print('ClassRoomCreateView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('not authenticated')
            return super(ClassRoomCreateView, self).get_login_url()
        return ''

    def get_context_data(self, **kwargs):
        context = super(ClassRoomCreateView, self).get_context_data(**kwargs)
        context['title'] = "Add Class Room"
        return context  

class ClassRoomUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''
    Create Class Room
    '''
    model = ClassRoom
    form_class = ClassRoomCreateForm
    success_url = reverse_lazy('classroomlist')
    template_name = 'Manager/classroom.html'
    raise_exception = True

    def test_func(self):
        print('ClassRoomCreateView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('not authenticated')
            return super(ClassRoomUpdateView, self).get_login_url()
        return ''
    
    def get_context_data(self, **kwargs):
        context = super(ClassRoomUpdateView, self).get_context_data(**kwargs)
        context['title'] = "Modify Class Room"
        return context  

class ClassRoomDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    '''
    Delete Class Room
    '''
    model = ClassRoom
    fields = ('name', 'school')
    context_object_name = 'classRoom'
    success_url = reverse_lazy('classroomlist')
    template_name = 'Manager/deleteclassroom.html'
    raise_exception = True

    def test_func(self):
        print('ClassRoomDeleteview UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    #def delete(self, request, *args, **kwargs):
        #return super().delete(request, *args, **kwargs)

class StudentListview(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''
    Students List
    '''
    model = Take    
    context_object_name = 'Students'
    template_name = 'studentlist.html'
    raise_exception = True

    def test_func(self):
        return True
    
    def get_queryset(self):
        course = Course.objects.get(id=self.kwargs['pk'])        
        return Take.objects.filter(course_id=course.id).order_by('student__first_name')
    
    def get_context_data(self, **kwargs):
        context = super(StudentListview, self).get_context_data(**kwargs)
        course = Course.objects.get(id=self.kwargs['pk'])     
        context['title'] = "Student List for {0}".format(course.name)
        return context 

class CourseListview(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''
    Course List
    '''
    model = Course
    ordering = ('name', )
    context_object_name = 'Courses'
    template_name = 'courselist.html'
    raise_exception = True

    def test_func(self):
        print('CourseListview UserType:{0}'.format(self.request.user.user_type))
        return True

    def get_queryset(self):
        print('CourseListview UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type == 1:            

LainSimpleGrades/Grades/templates/Manager/classroom.html
<!-- templates/Manager/classroom.html -->
{% extends 'base.html' %} {% block title %}Class Room{% endblock %} {% block content %}
<div class="w3-container w3-teal">
  <h2>
    <i class="fas fa-door-open" style="font-size:60px;color:rgb(208, 231, 231);text-shadow:2px 2px 4px #000000;"></i>
    </i>&nbsp &nbsp{{ title }}</h2>
</div>
</br>
<a class="w3-btn w3-block w3-teal w3-hover-text-aqua" href="{% url 'classroomlist' %}">Back to List</a>
<div>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input class="w3-btn w3-block w3-teal w3-hover-text-aqua" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

LainSimpleGrades/Grades/templates/Manager/classroomlist.html
<!-- templates/Manager/classroomlist.html -->
{% extends 'base.html' %} {% block title %}Class Room{% endblock %} {% block content %}
<div class="w3-container w3-teal">
  <h2>
    <i class="fas fa-door-open" style="font-size:60px;color:rgb(208, 231, 231);text-shadow:2px 2px 4px #000000;"></i>
    </i>&nbsp &nbspClass Room List</h2>
</div>
{% if user.is_authenticated %}
<div class="w3-responsive">
  <table class="w3-table-all w3-card-4 w3-hoverable w3-centered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>School</th>
        <th>City</th>
        <th colspan=2>Commands</th>
      </tr>
    </thead>
    <tbody>
      {% for classroom in ClassRooms %}
      <tr>
        <td class="align-middle">{{ classroom.id }}</td>
        <td class="align-middle">{{ classroom.name }}</td>
        <td class="align-middle">{{ classroom.school.name }}</td>
        <td class="align-middle">{{ classroom.school.get_city_display }}</td>
        <td class="align-middle">
          <a href="{% url 'editclassroom' classroom.pk %}">Modify</td>
        <td class="align-middle">
          <a href="{% url 'deleteclassroom' classroom.pk %}">Delete</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="6">No classrooms yet</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br/>
<a class="w3-btn w3-border w3-hover-text-blue" href="{% url 'addclassroom' %}">Add Class Room</a>
<br/> {% else %}
<p>You are not logged in</p>
{% endif %} {% endblock %}

LainSimpleGrades/Grades/templates/Manager/deleteclassroom.html
<!-- templates/Manager/deleteclassroom.html -->
{% extends 'base.html' %} {% block title %}Class Room{% endblock %} {% block content %}
<div class="w3-container w3-teal">
  <h2>
    <i class="fas fa-trash-alt" style="font-size:60px;color:rgb(208, 231, 231);text-shadow:2px 2px 4px #000000;"></i>
    </i>&nbsp &nbspDelete Class Room {{ classRoom.name }}</h2>
</div>
</br>
<a class="w3-btn w3-block w3-teal w3-hover-text-aqua" href="{% url 'classroomlist' %}">Back to List</a>
<div>
  <form method="post">
    {% csrf_token %} {{ form.as_p }} Are you sure you really want to delete Classroom {{ classRoom.name }} for school {{ classRoom.school
    }} ?
    <br/>
    <br/>
    <input class="w3-btn w3-block w3-teal w3-hover-text-aqua" type="submit" value="Delete">
  </form>
</div>
{% endblock %}

LainSimpleGrades/Grades/templates/Manager/deleteschool.html
<!-- templates/Manager/deleteschool.html -->
{% extends 'base.html' %} {% block title %}School{% endblock %} {% block content %}
<div class="w3-container w3-teal">
  <h2>
    <i class="fas fa-university" style="font-size:60px;color:rgb(208, 231, 231);text-shadow:2px 2px 4px #000000;"></i>
    </i>&nbsp &nbspDelete {{ school.name }}</h2>
</div>
</br>
<a class="w3-btn w3-block w3-teal w3-hover-text-aqua" href="{% url 'schoollist' %}">Back to List</a>
<div>
  <form method="post">
    {% csrf_token %} {{ form.as_p }} Are you sure you really want to delete school {{ school.name }}?
    <br/>
    <br/>
    <input class="w3-btn w3-block w3-teal w3-hover-text-aqua" type="submit" value="Delete">

  </form>
</div>
{% endblock %}

LainSimpleGrades/Grades/templates/Manager/school.html
<!-- templates/Manager/school.html -->
{% extends 'base.html' %} {% block title %}School{% endblock %} {% block content %}
<div class="w3-container w3-teal">
  <h2>
    <i class="fas fa-university" style="font-size:60px;color:rgb(208, 231, 231);text-shadow:2px 2px 4px #000000;"></i>
    </i>&nbsp &nbsp{{ title }}</h2>
</div>
</br>
<a class="w3-btn w3-block w3-teal w3-hover-text-aqua" href="{% url 'schoollist' %}">Back to List</a>
<div>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input class="w3-btn w3-block w3-teal w3-hover-text-aqua" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

LainSimpleGrades/Grades/templates/Manager/schoollist.html
<!-- templates/Manager/schoollist.html -->
{% extends 'base.html' %} {% block title %}School{% endblock %} {% block content %}
<div class="w3-container w3-teal">
  <h2>
    <i class="fas fa-university" style="font-size:60px;color:rgb(208, 231, 231);text-shadow:2px 2px 4px #000000;"></i>
    </i>&nbsp &nbspSchool List</h2>
</div>
{% if user.is_authenticated %}
<div class="w3-responsive">
  <table class="w3-table-all w3-card-4 w3-hoverable w3-centered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>City</th>
        <th colspan=2>Commands</th>
      </tr>
    </thead>
    <tbody>
      {% for school in Schools %}
      <tr>
        <td class="align-middle">{{ school.id }}</td>
        <td class="align-middle">{{ school.name }}</td>
        <td class="align-middle">{{ school.get_city_display }}</td>
        <td class="align-middle">
          <a href="{% url 'editschool' school.pk %}">Modify</td>
        <td class="align-middle">
          <a href="{% url 'deleteschool' school.pk %}">Delete</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="5">No schools yet</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br/>
<a class="w3-btn w3-border w3-hover-text-blue" href="{% url 'addschool' %}">Add School</a>
<br/> {% else %}
<p>You are not logged in</p>
{% endif %} {% endblock %}