LainSimpleGrades/Grades/urls.py
'''
urls.py - Django Standart File Url Routing

This file is part of Lain Simple Grades.

Lain Simple Grades is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Lain Simple Grades is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Lain Simple Grades.  If not, see <https://www.gnu.org/licenses/>.
'''
from django.urls import path
from . import views

#Common
urlpatterns = [
    path('', views.index, name='index'),    
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('userslist/', views.UserListView.as_view(), name='userslist'),
    path('studentlist/<int:pk>', views.StudentListview.as_view(), name='studentlist')
]

#Managers
urlpatterns += [
    path('schoollist/', views.SchoolListView.as_view(), name='schoollist'),
    path('addschool/', views.SchoolCreateView.as_view(), name='addschool'),
    path('editschool/<int:pk>/', views.SchoolUpdateView.as_view(), name='editschool'),
    path('deleteschool/<int:pk>/delete/', views.SchoolDeleteView.as_view(), name='deleteschool'),
    path('addclassroom/', views.ClassRoomCreateView.as_view(), name='addclassroom'),
    path('classroomlist', views.ClassRoomListView.as_view(), name='classroomlist'),
    path('editclassroom/<int:pk>/', views.ClassRoomUpdateView.as_view(), name='editclassroom'),
    path('deleteclassroom/<int:pk>/delete/', views.ClassRoomDeleteView.as_view(), name='deleteclassroom'),
]

#Lecturers
urlpatterns += [
    path('courselist/', views.CourseListview.as_view(), name='courselist'),
    path('addcourse/', views.CourseCreateView.as_view(), name='addcourse'),
    path('editcourse/<int:pk>/', views.CourseUpdateView.as_view(), name='editcourse'),
    path('deletecourse/<int:pk>/delete/', views.CourseDeleteView.as_view(), name='deletecourse'),    
    path('givegrades/<int:pk>', views.GiveGradesView.as_view(), name='givegrades'),    
]

#Students
urlpatterns += [
    path('enroll/<int:pk>/', views.Enroll, name='enroll'),
    path('takencourses/', views.TakenCoursesListView.as_view(), name='takencourses'),
]

LainSimpleGrades/LainSimpleGrades/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
urlpatterns += [
    path('grades/', include('Grades.urls')),
    path('', include('Grades.urls'))
]

urlpatterns += [    
    path('', include('django.contrib.auth.urls')),
]

LainSimpleGrades/Grades/models.py
'''
models.py - Django Standart File Models

This file is part of Lain Simple Grades.

Lain Simple Grades is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Lain Simple Grades is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Lain Simple Grades.  If not, see <https://www.gnu.org/licenses/>.
'''

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

class CustomUser(AbstractUser):
    '''
    Custom User Model for authentication
    '''
    USER_TYPE_CHOICES = (
        (0, 'Admin'),
        (1, 'Student'),
        (2, 'Lecturer'),   
        (3, 'Manager'),
    )

    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=0)
    def __str__(self):
        return self.username

class School(models.Model):
    '''
    School model
    '''
    name = models.CharField(max_length=50, help_text="Enter School Name")
    
    CITY_CHOICES = (        
        (1, 'Istanbul'),
        (2, 'London'),   
        (3, 'Tokyo'),
        (4, 'New York'),
        (5, 'Berlin'),
        (6, 'Moscow'),
    )

    city = models.PositiveSmallIntegerField(choices=CITY_CHOICES, default=1)
    
    def __str__(self):
        return self.name

class ClassRoom(models.Model):
    '''
    ClassRoom in school
    '''
    name = models.CharField(max_length=50, help_text="Enter Classroom Name")
    school = models.ForeignKey('School', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class Course(models.Model):
    '''
    Course model
    '''
    name = models.CharField(max_length=50, help_text='Enter Course Name')
    code = models.CharField(max_length=10, help_text='Enter Course Code')    
    classRoom = models.ForeignKey('ClassRoom', on_delete=models.SET_NULL, null=True, help_text='Select Class Room')
    lecturer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='Students', help_text='Students')

    def __str__(self):
        return "{0} ({1})".format(self.name, self.code)


class Take(models.Model):
    '''
    Take model. Student grades.
    '''
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    grade = models.PositiveIntegerField(blank=True, null=True, help_text='Grade', 
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)])
    

LainSimpleGrades/Grades/views.py
'''
Views.py - Django Standart File Views

This file is part of Lain Simple Grades.

Lain Simple Grades is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Lain Simple Grades is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Lain Simple Grades.  If not, see <https://www.gnu.org/licenses/>.
'''
from django.template import loader
from django.http import HttpResponse
from django import views
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.forms import modelformset_factory
from django.views.generic import (CreateView, DeleteView, ListView, FormView, UpdateView)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import  ClassRoom, School, Course, CustomUser, Take
from .forms import SignUpForm, SchoolCreateForm, ClassRoomCreateForm, CourseForm, GiveGradesForm

# Create your views here.
def index(request):
    '''
    Home Page
    '''
    print('index called')
    return render(request, 'index.html')

class SignUp(CreateView):
    '''
    New User Signup
    '''
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        role = form.cleaned_data['role']
        obj.user_type = role
        form.save()
        return super().form_valid(form)

class UserListView(LoginRequiredMixin, ListView):
    '''
    Users List
    '''
    model = CustomUser
    ordering = ('name', )
    context_object_name = 'Users'
    template_name = 'userslist.html'
    raise_exception = True

    def test_func(self):
        print('UserListview UserType:{0}'.format(self.request.user.user_type)) 
        return True

    def get_queryset(self):
        return CustomUser.objects.order_by('user_type')

class SchoolListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''
    School List
    '''
    model = School
    ordering = ('name', )
    context_object_name = 'Schools'
    template_name = 'Manager/schoollist.html'
    raise_exception = True

    def test_func(self):
        print('SchoolListview UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_queryset(self):
        return School.objects.order_by('name')

class SchoolCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    '''
    School Create
    '''
    model = School
    form_class = SchoolCreateForm
    template_name = 'Manager/school.html'
    success_url = reverse_lazy('schoollist')
    raise_exception = True

    def test_func(self):
        print('SchoolCreatView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('not authenticated')
            return super(SchoolCreateView, self).get_login_url()
        return ''      

    def get_context_data(self, **kwargs):
        context = super(SchoolCreateView, self).get_context_data(**kwargs)
        context['title'] = "Add School"
        return context  

class SchoolUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''
    Update School
    '''
    model = School
    form_class = SchoolCreateForm
    template_name = 'Manager/school.html'
    success_url = reverse_lazy('schoollist')
    raise_exception = True

    def test_func(self):
        print('SchoolUpdateView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True
    
    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('not authenticated')
            return super(SchoolUpdateView, self).get_login_url()
        return ''      

    def get_context_data(self, **kwargs):
        context = super(SchoolUpdateView, self).get_context_data(**kwargs)
        context['title'] = "Modify School"
        return context  

class SchoolDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    '''
    Delete School
    '''
    model = School
    fields = ('id', 'name', 'city')
    context_object_name = 'school'
    success_url = reverse_lazy('schoollist')
    template_name = 'Manager/deleteschool.html'
    raise_exception = True

    def test_func(self):
        print('SchoolDeleteView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

class ClassRoomListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''
    Class Room List
    '''
    model = ClassRoom
    ordering = ('name', )
    context_object_name = 'ClassRooms'
    template_name = 'Manager/classroomlist.html'
    raise_exception = True

    def test_func(self):
        print('ClassRoomListView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_queryset(self):
        return ClassRoom.objects.order_by('school')

class ClassRoomCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    '''
    Create Class Room
    '''
    model = ClassRoom
    form_class = ClassRoomCreateForm
    success_url = reverse_lazy('classroomlist')
    template_name = 'Manager/classroom.html'
    raise_exception = True

    def test_func(self):
        print('ClassRoomCreateView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('not authenticated')
            return super(ClassRoomCreateView, self).get_login_url()
        return ''

    def get_context_data(self, **kwargs):
        context = super(ClassRoomCreateView, self).get_context_data(**kwargs)
        context['title'] = "Add Class Room"
        return context  

class ClassRoomUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''
    Create Class Room
    '''
    model = ClassRoom
    form_class = ClassRoomCreateForm
    success_url = reverse_lazy('classroomlist')
    template_name = 'Manager/classroom.html'
    raise_exception = True

    def test_func(self):
        print('ClassRoomCreateView UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('not authenticated')
            return super(ClassRoomUpdateView, self).get_login_url()
        return ''
    
    def get_context_data(self, **kwargs):
        context = super(ClassRoomUpdateView, self).get_context_data(**kwargs)
        context['title'] = "Modify Class Room"
        return context  

class ClassRoomDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    '''
    Delete Class Room
    '''
    model = ClassRoom
    fields = ('name', 'school')
    context_object_name = 'classRoom'
    success_url = reverse_lazy('classroomlist')
    template_name = 'Manager/deleteclassroom.html'
    raise_exception = True

    def test_func(self):
        print('ClassRoomDeleteview UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 3:
            print('User type mismatch, test_func denied')
            return False
        return True

    #def delete(self, request, *args, **kwargs):
        #return super().delete(request, *args, **kwargs)

class StudentListview(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''
    Students List
    '''
    model = Take    
    context_object_name = 'Students'
    template_name = 'studentlist.html'
    raise_exception = True

    def test_func(self):
        return True
    
    def get_queryset(self):
        course = Course.objects.get(id=self.kwargs['pk'])        
        return Take.objects.filter(course_id=course.id).order_by('student__first_name')
    
    def get_context_data(self, **kwargs):
        context = super(StudentListview, self).get_context_data(**kwargs)
        course = Course.objects.get(id=self.kwargs['pk'])     
        context['title'] = "Student List for {0}".format(course.name)
        return context 

class CourseListview(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''
    Course List
    '''
    model = Course
    ordering = ('name', )
    context_object_name = 'Courses'
    template_name = 'courselist.html'
    raise_exception = True

    def test_func(self):
        print('CourseListview UserType:{0}'.format(self.request.user.user_type))
        return True

    def get_queryset(self):
        print('CourseListview UserType:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type == 1:            

LainSimpleGrades/Grades/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<title>Lain Simple Grades</title>
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="text/css" type="image/x-icon" href="{% static 'images/favicon.png' %}" />
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
  crossorigin="anonymous">
<style>
  html,
  body,
  h1,
  h2,
  h3,
  h4,
  h5 {
    font-family: "Arial", sans-serif
  }
</style>

<body class="w3-light-grey">

  <!-- Top container -->
  <div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
    <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();">
      <i class="fa fa-bars"></i>  Menu</button>
    {% if user.is_authenticated %}
    <span class="w3-bar-item w3-right">
      <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-padding"> |{{ user.username }}|  Logout
        <i class="fa fa-sign-out-alt fa-fw"></i>
      </a>
    </span>
    {% else %}
    <span class="w3-bar-item w3-right">
      <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-sign-in-alt fa-fw"></i>  Login</a>
    </span>
    <span class="w3-bar-item w3-right">
      <a href="{% url 'signup' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-user-plus fa-fw"></i>  Signup</a>
    </span>
    {% endif %}
  </div>

  <!-- Sidebar/menu -->
  <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar">
    <br>
    <div class="w3-container w3-row">
      <div class="w3-col s4">
        {% if user.is_authenticated %} {% if user.user_type == 0 %}
        <i class="fa fa-user-cog" style="font-size:60px;color:teal;text-shadow:2px 2px 4px #000000;"></i>
        {% endif %} {% if user.user_type == 1 %}
        <i class="fa fa-user-graduate" style="font-size:60px;color:teal;text-shadow:2px 2px 4px #000000;"></i>
        {% endif %} {% if user.user_type == 2 %}
        <i class="fa fa-chalkboard-teacher" style="font-size:60px;color:teal;text-shadow:2px 2px 4px #000000;"></i>
        {% endif %} {% if user.user_type == 3 %}
        <i class="fa fa-user-tie" style="font-size:60px;color:teal;text-shadow:2px 2px 4px #000000;"></i>
        {% endif %} {% else %}
        <i class="fa fa-user-ninja" style="font-size:60px;color:teal;text-shadow:2px 2px 4px #000000;"></i>
        {% endif %}
      </div>
      <div class="w3-col s8 w3-bar">
        {% if user.is_authenticated %}
        <span>Welcome,
          <strong>{{ user.first_name }} {{ user.last_name }}</strong>
        </span>
        <br>
        <span>Logged in as
          <strong>{{ user.get_user_type_display }}</strong>
        </span>
        <br>
        <!--a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a-->
        {% else %}
        <span>You are anonymous</span>
        <br> {% endif %}

      </div>
    </div>

    <hr>
    <div class="w3-container">
      <h5>Dashboard</h5>
    </div>
    <div class="w3-bar-block">
      <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu">
        <i class="fa fa-remove fa-fw"></i>  Close Menu</a>
      <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-home fa-fw"></i>  Home</a>
      {% if user.is_authenticated %} {% if user.user_type == 0 %}
      <a href="{% url 'admin:index' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-cogs fa-fw"></i>  Administration</a>
      {% endif %} {% if user.user_type == 1 %}
      <a href="{% url 'takencourses' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-cogs fa-fw"></i>  Taken Courses</a>
      {% endif %} {% if user.user_type == 2 %} {% endif %} {% if user.user_type == 3 %}
      <a href="{% url 'schoollist' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-university fa-fw"></i>  Schools</a>
      <a href="{% url 'classroomlist' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-door-open fa-fw"></i>  Class Rooms</a>
      {% endif %}
      <a href="{% url 'courselist' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-book fa-fw"></i>  Courses</a>
      <a href="{% url 'userslist' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-users fa-fw"></i>  Users List</a>
      <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-sign-out-alt fa-fw"></i>  Logout</a>
      {% else %}
      <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-sign-in-alt fa-fw"></i>  Login</a>
      <a href="{% url 'signup' %}" class="w3-bar-item w3-button w3-padding">
        <i class="fa fa-user-plus fa-fw"></i>  Signup</a>
      {% endif %}
    </div>
  </nav>

  <!-- Overlay effect when opening sidebar on small screens -->
  <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu"
    id="myOverlay"></div>

  <!-- !PAGE CONTENT! -->
  <div class="w3-main" style="margin-left:300px;margin-top:43px;">
    <!-- Header -->
    <!--header class="w3-container" style="padding-top:22px">
    <h5><b><i class="fa fa-desktop"></i> Grades Demo</b></h5>
  </header-->
    <div class="w3-container w3-padding-16">
      {% block content %} {% endblock %}
    </div>
    <!-- Footer -->
    <footer class="w3-container w3-padding-16 w3-light-gray">
      <p>Lain Simple Grades - Copyright © 2018 Ayhan Avcı Home:
        <a href="https://lain.run/" target="_blank">Lain.run</a>. View source on 
        <a href="https://github.com/ayhanavci/LainSimpleGrades" target="_blank">Github</a>
      </p>     
      
      <p>
        <a href="https://www.gnu.org/licenses/gpl.html" target="_blank">
          <img src="{% static 'images/gpl-v3-logo.svg' %}" width="10%" height="10%" alt="GNU General Public License">
        </a>
      </p>
    
    </footer>

    <!-- End page content -->
  </div>

  <script>
    // Get the Sidebar
    var mySidebar = document.getElementById("mySidebar");

    // Get the DIV with overlay effect
    var overlayBg = document.getElementById("myOverlay");

    // Toggle between showing and hiding the sidebar, and add overlay effect
    function w3_open() {
      if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
      } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
      }
    }

    // Close the sidebar with the close button
    function w3_close() {
      mySidebar.style.display = "none";
      overlayBg.style.display = "none";
    }
  </script>

</body>

</html>

LainSimpleGrades/Grades/templates/courselist.html
<!-- templates/courselist.html -->
{% extends 'base.html' %} {% block title %}Course{% endblock %} {% block content %}
<div class="w3-container w3-teal">
  <h2>
    <i class="fas fa-list-ul" style="font-size:60px;color:rgb(208, 231, 231);text-shadow:2px 2px 4px #000000;"></i>
    </i>&nbsp &nbspCourse List</h2>
</div>
{% if user.is_authenticated %}
<div class="w3-responsive">
  <table class="w3-table-all w3-card-4 w3-hoverable w3-centered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Code</th>
        <th>Name</th>
        <th>Class Room</th>
        <th>Lecturer</th>
        <th colspan=4>Commands</th>
      </tr>
    </thead>
    <tbody>
      {% for course in Courses %}
      <tr>
        <td class="align-middle">{{ course.id }}</td>
        <td class="align-middle">{{ course.code }}</td>
        <td class="align-middle">{{ course.name }}</td>
        <td class="align-middle">{{ course.classRoom }}</td>
        <td class="align-middle">{{ course.lecturer.first_name }} {{ course.lecturer.last_name }}</td>
        {% if user.user_type == 2 %}
        <td class="align-middle">
          <a href="{% url 'studentlist' course.pk %}">View Students
        </td>
        {% elif user.user_type == 1 %}
        <td class="align-middle">
          <a href="{% url 'enroll' course.pk %}">Enroll
        </td>
        {% else %}
        <td class="align-middle">
          <a href="{% url 'studentlist' course.pk %}">View Students
        </td>

        {% endif %} {% if course.lecturer == user %}
        <td class="align-middle">
          <a href="{% url 'givegrades' course.pk %}">Grade
        </td>
        <td class="align-middle">
          <a href="{% url 'editcourse' course.pk %}">Modify
        </td>
        <td class="align-middle">
          <a href="{% url 'deletecourse' course.pk %}">Delete
        </td>
        {% else %}
        <td class="align-middle"></td>
        <td class="align-middle"></td>
        <td class="align-middle"></td>
        {% endif %}
      </tr>
      {% empty %}
      <tr>
        <td>No courses yet</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br/> {% if user.user_type == 2 %}
<a class="w3-btn w3-border w3-hover-text-blue" href="{% url 'addcourse' %}">Add Course</a>
{% endif %}
<br/> {% else %}
<p>You are not logged in</p>
{% endif %}
<p>
  Lecturers can Add, Modify, Delete Courses and View Enrolled Students</br>
  Studens can Enroll Courses</br>
  Admins and Managers can View Enrolled Students
</p>
{% endblock %}

LainSimpleGrades/Grades/templates/userslist.html
<!-- templates/userslist.html -->
{% extends 'base.html' %}

{% block title %}Users{% endblock %}

{% block content %}
<div class="w3-container w3-teal">
    <h2><i class="fas fa-users" style="font-size:60px;color:rgb(208, 231, 231);text-shadow:2px 2px 4px #000000;"></i></i>&nbsp &nbspUsers List</h2>    
</div> 
{% if user.is_authenticated %}   
<div class = "w3-responsive">
    <table class="w3-table-all w3-card-4 w3-hoverable w3-centered">
    <thead>
      <tr>        
        <th>ID</th>
        <th>Name</th> 
        <th>Last Name</th>      
        <th>Type</th>   
        <th>User Name</th>         
        <th>Email</th> 
        <th>Date Joined</th>
        <th>Last Login</th>             
      </tr>
    </thead>
    <tbody>
      {% for user in Users %}
      <tr>        
        <td class="align-middle">{{ user.id }}</td>
        <td class="align-middle">{{ user.first_name }}</td> 
        <td class="align-middle">{{ user.last_name }}</td>  
        <td class="align-middle">{{ user.get_user_type_display }}</td>          
        <td class="align-middle">{{ user.username }}</td>                           
        <td class="align-middle">{{ user.email }}</td>       
        <td class="align-middle">{{ user.date_joined }}</td>       
        <td class="align-middle">{{ user.last_login }}</td>       
      </tr>
      {% empty %}
      <tr>
        <td>No users yet</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>  
</div>   
{% else %}
  <p>You are not logged in</p>  
{% endif %}
{% endblock %}